### ISSUE TITLE
Handle 0 values

### ISSUE THREAD

**Issue by ebrelsford** [informeren/qgis-cartogram#5]
I get a `ZeroDivisionError` in the logs when I try to use this plugin with some features where the area column has a 0 in it. It would be great if the plugin could handle this more gracefully (eg by ignoring or removing those features?).

**Comment by wulff** [comment]
I think it would make sense to just ignore those features, as long as they are still affected by the surrounding features (to avoid weird gaps in the geometry).

**Comment by wulff** [comment]
I'm working on this issue over on #4.

Closing this as a duplicate.
